parallel: true
format: progress

ignore:
  - ".bridgetown-build/**/*"
  - ".bridgetown-cache/**/*"
  - "node_modules/**/*"
  - ".github/**/*"
  - ".vscode/**/*"
  - "src/**/*":
    - Layout/LeadingCommentSpace
